### ISSUE TITLE
Add python preview support.

### ISSUE THREAD

**Issue by zet4** [zedapp/zed#187]
Could it be possible to add ability to compile in python mode? I know there is GoPy project that can compile Python code from in Go code, so it technically wouldn't be complicated to implement it.

Also any other way to manually configure compile tool? in Sublime Text you could simply create those build scripts which the system followed on key press, is there such available yet?

**Comment by domenkozar** [comment]
https://github.com/domenkozar/zed-flake8 also handles compile errors, otherwise you can run `python -m compileall <file>`
