### ISSUE TITLE
File sometimes doesn't save

### ISSUE THREAD

**Issue by eric1234** [zedapp/zed#423]
I have recently (maybe last week or two) been getting an issue where I make a change but the file on disk doesn't actually change. The solution is to make some other change to the file then undo that change. At that point the change is persisted to disk.

I don't think I ever got this issue when I first started using Zed so I think it is due to a recent change. It doesn't happen often so I'm not sure the best way to help provide info that would help in debugging this issue.

**Comment by zefhemel** [comment]
Please reopen if this occurs again.
