### ISSUE TITLE
In vim keybinding, `^` and `I` is not correct

### ISSUE THREAD

**Issue by farnoy** [zedapp/zed#478]
It depends where the cursor is on the line.

Example (`^` is the cursor):

```
  some indented text
^
```

Pressing `^` or `I` now will move to the first non-blank character of the line, which is the same as in Vim:

```
  some indented text
  ^
```

Repeating it again will move to the first character of the line:

```
  some indented text
^
```

Source: <http://vimdoc.sourceforge.net/htmldoc/motion.html#^>

Is this a bug in Ace, or Zed?

**Comment by zefhemel** [comment]
It's a bug in ACE, can you report it there?

**Comment by farnoy** [comment]
I'll close this then, thanks.

**Comment by farnoy** [comment]
This bug was fixed in the new version of Ace, can we update it in Zed?

**Comment by farnoy** [comment]
hmm, I see you've already updated it, <https://github.com/zedapp/zed/commit/94a15f6bb3d6d6309c6f7874cbc7fbf0aec306b1>, I'll check if it works.

**Comment by farnoy** [comment]
yup, all is well, I'll just use the locally built version until a new one hits the chrome webstore. Thanks!
