### ISSUE TITLE
Does Zed has anything similiar to Emacs' Flycheck (or Flymake)?

### ISSUE THREAD

**Issue by usharf** [zedapp/zed#480]
Is there a way to simply had custome ad-hoc checkers to particular modes?

**Comment by zefhemel** [comment]
Definitely and many modes do, from the top of my head: Python, JavaScript, PHP, CSS, Lua and probably more. What language do you need it for?

**Comment by zefhemel** [comment]
Please reopen if this is not what you were refering to.
