### ISSUE TITLE
Install issue with Bitnami Stack

### ISSUE THREAD

**Issue by Speaker4TheUndead** [zedapp/zed#490]
The Command "curl http://get.zedapp.org | bash"  returns 
![f0db5a1ea3bca7ac0943f4f74abbfe48](https://cloud.githubusercontent.com/assets/7908301/5770801/09a157b2-9cff-11e4-9150-e9bf3b6cedec.png)

Though shouldn't it be recognized as Linux-64? And can I get an Easy fix to this?

**Comment by zefhemel** [comment]
You are running the curl command as root, there's no point in that. If you need root permissions to write to the current directory, run `bash` as root. So:

    curl http://get.zedapp.org | sudo bash

**Comment by zefhemel** [comment]
Please reopen this issue if this doesn't fix the problem for you.
