### ISSUE TITLE
Snapshot Profiler on Chrome version?

### ISSUE THREAD

**Issue by eric1234** [zedapp/zed#492]
Lately on my computer I've been getting a problem where the load continues to increase slowely until my system become almost unusable. It's been a bit hard to nail down where the problem is. My three primary culprits are Firefox, Gnome or Zed. I think I have narrowed it down to Zed so I want to dig in to see if I can confirm and figure out why. Is there any way to see what Zed is doing while running (i.e. some sort of debugger profiler snapshot)? If it helps I am running the Chrome version of Zed.

**Comment by zefhemel** [comment]
Yep, you can right click Zed an pick "Inspect element" to bring up a Chrome inspector window with all usual web debugging tools available. It's possible you may have to enable "Developer mode" under the three-lined menu > More tools > Extensions for this option to appear.

Let me know what you find!

**Comment by eric1234** [comment]
K, closing this for now until I find out if it is Zed causing the problem.
