### ISSUE TITLE
main editing area doesn't honor the background color specified in the theme

### ISSUE THREAD

**Issue by htejun** [zedapp/zed#496]
I've been trying out zed on chrome Version 40.0.2214.93 (64-bit) on a fedora 21 box. It works well but for some reason the background color of the main editing area is stuck at #333333 if a dark theme is selected regardless of the background color specified by the theme. I'm attaching a screenshot w/ the clouds midnight theme which looks weird due to the low contrast from the too bright background.

Thanks a lot.
![screenshot from 2015-01-29 06 45 46](https://cloud.githubusercontent.com/assets/1051723/5957127/1e388bf8-a783-11e4-8fc7-57d9110fb436.png)

**Comment by zefhemel** [comment]
This *should* be fixed by @TheKiteEatingTree can you verify? This will be part of 1.1. Please reopen if it's not fixed.

**Comment by htejun** [comment]
Yes, it's fixed. Thank you very much.
