### ISSUE TITLE
Zed does not start anymore

### ISSUE THREAD

**Issue by Fusl** [zedapp/zed#497]
Hi,

I built the most recent git master branch and installed it, now Zed won't start anymore.

![Screenshot](https://scr.meo.ws/snapshot/2015-01-30-12-49-12-ekzzVO8t.png)

That's all I see in the console:

```
 _ zed
WARNING: Both the zed directory and its parent should be writable by
the user who runs Zed in order for auto-update to work. In your current
setup this is NOT the case, please move Zed somewhere else or change
permissions.
Checking for update
Caught exception: TypeError: Cannot read property 'length' of undefinedCurrent version 1.0.1 new version 1.0.1
No upgrade required
```

**Comment by zefhemel** [comment]
Presumably you're running this on Linux, can you try renaming the ~/.config/zed to somewhere else and see that somehow fixes it?

Also did you run `git submodule --update --recursive` to check out submodules to the correct commit?

**Comment by Fusl** [comment]
Running ```git submodule --update --recursive``` fixed this. Sorry for bothering :)

**Comment by zefhemel** [comment]
No problem at all.
