### ISSUE TITLE
edit a file only

### ISSUE THREAD

**Issue by martindufresne** [zedapp/zed#506]
I use Zed main code editor. But sometimes I just need to edit a file on my machine. Is it possible to do without importing a directory and if not, is this something that could be done?

**Comment by zefhemel** [comment]
This is not currently possible, but wouldn't be very hard to add. What version of Zed are you using? The Chrome app or standalone? Also, what would expect the flow to be. Should there be a "Open a File" option in the project picker which pops up a file picker or something?

**Comment by martindufresne** [comment]
I use the Chrome app. For me, a simple "Open a File" option in the project picker would be perfect! Thank you for the speed with which you answer questions. It is much appreciated.

**Comment by zefhemel** [comment]
Implemented, will be part of 1.1. Only available in the Chrome App for now, if there's interest in this for standalone I can implement that as well.
