### ISSUE TITLE
Impossible to open last-opened folder in Zedd

### ISSUE THREAD

**Issue by rfilmyer** [zedapp/zed#513]
(Zedd on a Mac, 10.10, Zed client on a Chromebook)

When I try to open a folder through Zedd, the last option is selected by default. Unfortunately, this means that I can't actually select it, and any time I try to click something else to lose focus, it opens that folder instead.

Example:
![screenshot 2015-02-25 at 12 45 07 pm](https://cloud.githubusercontent.com/assets/5913205/6376582/c9e77e36-bcec-11e4-9527-80260776e975.png)
(Let's work on this project today!)

![screenshot 2015-02-25 at 12 45 29 pm](https://cloud.githubusercontent.com/assets/5913205/6376592/e0b984d8-bcec-11e4-9dd5-efac70d7ead7.png)
(But when I click, it just expands the folder!)

![screenshot 2015-02-25 at 12 51 06 pm](https://cloud.githubusercontent.com/assets/5913205/6376608/ff60a15a-bcec-11e4-8d24-42b69d676d1e.png)
(And when I click on `cover-letter` to lose focus, it just opens that folder instead!)

**Comment by zefhemel** [comment]
Yeah I noticed this at some point, then forgot about it again. Thanks for reporting, I'll look into it.

**Comment by zefhemel** [comment]
Fixed on master branch.
